# Generated by Django 5.0.2 on 2024-02-08 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('id_type', models.CharField(choices=[('NATIONAL ID', 'NATIONAL ID'), ('PASSPORT', 'PASSPORT'), ('DRIVING PERMIT', 'DRIVING PERMIT')], max_length=200, null=True)),
                ('id_number', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=200, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('district', models.CharField(choices=[('Abim', 'Abim'), ('Adjumani', 'Adjumani'), ('Agago', 'Agago'), ('Alebtong', 'Alebtong'), ('Amolatar', 'Amolatar'), ('Amudat', 'Amudat'), ('Amuria', 'Amuria'), ('Amuru', 'Amuru'), ('Apac', 'Apac'), ('Arua', 'Arua'), ('Budaka', 'Budaka'), ('Bududa', 'Bududa'), ('Bugiri', 'Bugiri'), ('Bugweri', 'Bugweri'), ('Buikwe', 'Buikwe'), ('Bukedea', 'Bukedea'), ('Bukomansimbi', 'Bukomansimbi'), ('Bukwa', 'Bukwa'), ('Bulambuli', 'Bulambuli'), ('Buliisa', 'Buliisa'), ('Bundibugyo', 'Bundibugyo'), ('Bunyangabu', 'Bunyangabu'), ('Bushenyi', 'Bushenyi'), ('Busia', 'Busia'), ('Butebo', 'Butebo'), ('Buvuma', 'Buvuma'), ('Buyende', 'Buyende'), ('Dokolo', 'Dokolo'), ('Gomba', 'Gomba'), ('Gulu', 'Gulu'), ('Hoima', 'Hoima'), ('Ibanda', 'Ibanda'), ('Iganga', 'Iganga'), ('Isingiro', 'Isingiro'), ('Jinja', 'Jinja'), ('Kaabong', 'Kaabong'), ('Kabale', 'Kabale'), ('Kabarole', 'Kabarole'), ('Kaberamaido', 'Kaberamaido'), ('Kagadi', 'Kagadi'), ('Kakumiro', 'Kakumiro'), ('Kalangala', 'Kalangala'), ('Kaliro', 'Kaliro'), ('Kalungu', 'Kalungu'), ('Kampala', 'Kampala'), ('Kamuli', 'Kamuli'), ('Kamwenge', 'Kamwenge'), ('Kanungu', 'Kanungu'), ('Kapchorwa', 'Kapchorwa'), ('Kapelebyong', 'Kapelebyong'), ('Kasanda', 'Kasanda'), ('Kasese', 'Kasese'), ('Katakwi', 'Katakwi'), ('Kayunga', 'Kayunga'), ('Kibaale', 'Kibaale'), ('Kiboga', 'Kiboga'), ('Kibuku', 'Kibuku'), ('Kikuube', 'Kikuube'), ('Kiruhura', 'Kiruhura'), ('Kiryandongo', 'Kiryandongo'), ('Kisoro', 'Kisoro'), ('Kitgum', 'Kitgum'), ('Koboko', 'Koboko'), ('Kole', 'Kole'), ('Kotido', 'Kotido'), ('Kumi', 'Kumi'), ('Kwania', 'Kwania'), ('Kween', 'Kween'), ('Kyankwanzi', 'Kyankwanzi'), ('Kyegegwa', 'Kyegegwa'), ('Kyenjojo', 'Kyenjojo'), ('Kyotera', 'Kyotera'), ('Lamwo', 'Lamwo'), ('Lira', 'Lira'), ('Luuka', 'Luuka'), ('Luwero', 'Luwero'), ('Lwengo', 'Lwengo'), ('Lyantonde', 'Lyantonde'), ('Manafwa', 'Manafwa'), ('Maracha', 'Maracha'), ('Masaka', 'Masaka'), ('Masindi', 'Masindi'), ('Mayuge', 'Mayuge'), ('Mbale', 'Mbale'), ('Mbarara', 'Mbarara'), ('Mitooma', 'Mitooma'), ('Mityana', 'Mityana'), ('Moroto', 'Moroto'), ('Moyo', 'Moyo'), ('Mpigi', 'Mpigi'), ('Mubende', 'Mubende'), ('Mukono', 'Mukono'), ('Nabilatuk', 'Nabilatuk'), ('Nakapiripirit', 'Nakapiripirit'), ('Nakaseke', 'Nakaseke'), ('Nakasongola', 'Nakasongola'), ('Namayingo', 'Namayingo'), ('Namisindwa', 'Namisindwa'), ('Namutumba', 'Namutumba'), ('Napak', 'Napak'), ('Nebbi', 'Nebbi'), ('Ngora', 'Ngora'), ('Ntoroko', 'Ntoroko'), ('Ntungamo', 'Ntungamo'), ('Nwoya', 'Nwoya'), ('Omoro', 'Omoro'), ('Otuke', 'Otuke'), ('Oyam', 'Oyam'), ('Pader', 'Pader'), ('Pakwach', 'Pakwach'), ('Pallisa', 'Pallisa'), ('Rakai', 'Rakai'), ('Rubanda', 'Rubanda'), ('Rubirizi', 'Rubirizi'), ('Rukiga', 'Rukiga'), ('Rukungiri', 'Rukungiri'), ('Sembabule', 'Sembabule'), ('Serere', 'Serere'), ('Sheema', 'Sheema'), ('Sironko', 'Sironko'), ('Soroti', 'Soroti'), ('Tororo', 'Tororo'), ('Wakiso', 'Wakiso'), ('Yumbe', 'Yumbe'), ('Zombo', 'Zombo')], max_length=200, null=True)),
                ('county', models.CharField(max_length=200, null=True)),
                ('subcounty', models.CharField(max_length=200, null=True)),
                ('parish', models.CharField(max_length=200, null=True)),
                ('village', models.CharField(max_length=200, null=True)),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('opening_balance', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('next_of_keen_first_name', models.CharField(max_length=200, null=True)),
                ('next_of_keen_last_name', models.CharField(max_length=200, null=True)),
                ('next_of_keen_phone', models.CharField(max_length=200, null=True)),
                ('next_of_keen_relationship', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING', 'PENDING')], max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('date_of_loan_application', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_repayemnt', models.DateField(null=True)),
                ('intrest_rate', models.CharField(max_length=200, null=True)),
                ('repay_in', models.CharField(choices=[('DAYS', 'DAYS'), ('MONTHS', 'MONTHS'), ('YEARS', 'YEARS')], max_length=200)),
                ('status', models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('PENDING', 'PENDING')], max_length=200)),
                ('collateral1', models.CharField(max_length=200, null=True)),
                ('collateral2', models.CharField(max_length=200, null=True)),
                ('reason', models.TextField(max_length=1000, null=True)),
                ('member_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teleka.member')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('date_of_transaction', models.DateTimeField(auto_now=True, null=True)),
                ('deposited_by', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('PENDING', 'PENDING')], max_length=200)),
                ('member_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teleka.member')),
            ],
        ),
        migrations.CreateModel(
            name='RepayLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('date_of_loan_repayment', models.DateTimeField(auto_now=True, null=True)),
                ('repay_in', models.CharField(max_length=200, null=True)),
                ('paid_by', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('PENDING', 'PENDING')], max_length=200)),
                ('member_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teleka.member')),
            ],
        ),
        migrations.CreateModel(
            name='SaccoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('date_of_transaction', models.DateTimeField(auto_now=True, null=True)),
                ('withdrawn_by', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('PENDING', 'PENDING')], max_length=200)),
                ('member_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teleka.member')),
            ],
        ),
    ]
